
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Root@123

development:
  <<: *default
  database: learn_ecommerce_development

test:
  <<: *default
  database: learn_ecommerce_test


production:
  <<: *default
  database: learn_ecommerce_production
  username: learn_ecommerce
  password: <%= ENV["LEARN_ECOMMERCE_DATABASE_PASSWORD"] %>
